### ISSUE TITLE
cree des comptes utilisateur 

### ISSUE THREAD

**Issue by Dmcviper** [TRAPTAProject/score-trapta#1]
bonjour,
je suis archer et je voulais savoir comment cree un compte utilisateur 
Cordialement

**Comment by PierreOc** [comment]
il n'y a pas plus de compte utilisateur avec TRAPTA Cloud Simple  https://trapta.fr/trapta_score_simple.htm

En revanche, avec TRAPTA Cloud 2.2 ou 2.2 en mode multi concours, il faut un site avec un hébergement comportant une base MySQL https://trapta.fr/trapta_cloud.htm#mysql
